---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task

platforms:
  - name: windows-2012r2
  

suites:
  - name: default
    run_list:
      - recipe[webapp-windows::default]
    attributes:
        sql_server:
            sysadmin: ['vagrant']
