name 'webapp-windows'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures webapp-windows'
long_description 'Installs/Configures webapp-windows'
version '0.2.2'

depends 'sql_server', '~> 2.4.0'
depends 'iis', '~> 4.1.5'
