---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

#network:
#- ["forwarded_port", {guest: 80, host: 8080}]
#- ["private_network", { ip: "192.168.33.33" }]
     
provisioner:
  name: chef_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.33"}]  

suites:
  - name: default
    data_bags_path: "../../data_bags"
    run_list:
       - recipe[webapp-linux::default]
    provisioner:
        encrypted_data_bag_secret_key_path: "/Users/darodecap/chef-repo/encrypted_data_bag_secret"
    attributes:
        webapp-linux:
            passwords:
                secret_path: '/tmp/kitchen/encrypted_data_bag_secret'
